# Pandas Excercise

In this excercise we modify a dataset and answer few questions
- What is the total population in capital region (Helsinki, Espoo, Vantaa, Kauniainen)
- What is the muncipality where the minimum population resides
- Where is the highest Työllisyysaste, %
- Where is the lowest Työllisyysaste, %

I am using pivot table to handle data

Tässä tehtävässä muokataan ensin excel-talukko sopivaan muotoon. 
Taulukon tilastot pitää muuttaa ensin pivot-taulukoksi, 
jotta dataa voidaan sen jälkeen analysoida.

In [2]:
import pandas as pd

# DataFramen muokkaus

In [3]:
df = pd.read_excel("Kunnat2.xlsx", header=2, skipfooter=46)

In [4]:
df

           Unnamed: 0                                Unnamed: 1     2017
0                Akaa                                  Väkiluku  16769.0
1                 NaN  Väkiluvun muutos edellisestä vuodesta, %     -0.9
2                 NaN                         Työllisyysaste, %     71.9
3                 NaN                 Taloudellinen huoltosuhde    144.7
4            Alajärvi                                  Väkiluku   9831.0
...               ...                                       ...      ...
1595              NaN                 Taloudellinen huoltosuhde     96.5
1596  Ålands skärgård                                  Väkiluku   2056.0
1597              NaN  Väkiluvun muutos edellisestä vuodesta, %     -3.1
1598              NaN                         Työllisyysaste, %     82.7
1599              NaN                 Taloudellinen huoltosuhde    118.7

[1600 rows x 3 columns]

In [5]:
df.fillna(method="ffill", inplace=True)
df

            Unnamed: 0                                Unnamed: 1     2017
0                 Akaa                                  Väkiluku  16769.0
1                 Akaa  Väkiluvun muutos edellisestä vuodesta, %     -0.9
2                 Akaa                         Työllisyysaste, %     71.9
3                 Akaa                 Taloudellinen huoltosuhde    144.7
4             Alajärvi                                  Väkiluku   9831.0
...                ...                                       ...      ...
1595  Ålands landsbygd                 Taloudellinen huoltosuhde     96.5
1596   Ålands skärgård                                  Väkiluku   2056.0
1597   Ålands skärgård  Väkiluvun muutos edellisestä vuodesta, %     -3.1
1598   Ålands skärgård                         Työllisyysaste, %     82.7
1599   Ålands skärgård                 Taloudellinen huoltosuhde    118.7

[1600 rows x 3 columns]

In [6]:
df.rename(columns={"Unnamed: 0":"Kaupunki","Unnamed: 1":"Tilasto"}, inplace=True)
df

              Kaupunki                                   Tilasto     2017
0                 Akaa                                  Väkiluku  16769.0
1                 Akaa  Väkiluvun muutos edellisestä vuodesta, %     -0.9
2                 Akaa                         Työllisyysaste, %     71.9
3                 Akaa                 Taloudellinen huoltosuhde    144.7
4             Alajärvi                                  Väkiluku   9831.0
...                ...                                       ...      ...
1595  Ålands landsbygd                 Taloudellinen huoltosuhde     96.5
1596   Ålands skärgård                                  Väkiluku   2056.0
1597   Ålands skärgård  Väkiluvun muutos edellisestä vuodesta, %     -3.1
1598   Ålands skärgård                         Työllisyysaste, %     82.7
1599   Ålands skärgård                 Taloudellinen huoltosuhde    118.7

[1600 rows x 3 columns]

# Kaupunkien ja kuntien erottelu

Erotellaan kaupungit, seutukunnat sekä maakunnat. Käytetään pivot taulukointia tilastojen analysoimiseen

In [16]:
#erotellaan kaupungit
kaupungit = df.head(1244)
kaupungit = kaupungit.pivot(index="Kaupunki", columns="Tilasto", values="2017")
kaupungit

Tilasto,Taloudellinen huoltosuhde,"Työllisyysaste, %",Väkiluku,"Väkiluvun muutos edellisestä vuodesta, %"
Kaupunki,,,,
Akaa,144.7,71.9,16769.0,-0.9
Alajärvi,180.2,67.7,9831.0,-0.7
Alavieska,160.0,71.5,2610.0,-1.1
Alavus,169.0,69.5,11713.0,-1.6
Asikkala,176.0,69.1,8248.0,-0.9
...,...,...,...,...
Ylivieska,149.7,70.9,15251.0,0.3
Ylöjärvi,127.4,76.6,32878.0,0.2
Ypäjä,145.0,71.2,2372.0,-0.4
Ähtäri,172.7,68.9,5906.0,-1.3
Äänekoski,179.9,65.2,19144.0,-1.2

In [14]:
#erotellaan seutukunnat
seutukunnat = df.iloc[1320:]
seutukunnat = seutukunnat.pivot(index="Kaupunki", columns="Tilasto", values="2017")
seutukunnat

Tilasto,Taloudellinen huoltosuhde,"Työllisyysaste, %",Väkiluku,"Väkiluvun muutos edellisestä vuodesta, %"
Kaupunki,,,,
Etelä-Pirkanmaan seutukunta,155.6,70.3,42734.0,-0.9
Forssan seutukunta,154.0,70.0,33288.0,-1.0
Haapavesi-Siikalatvan seutukunta,175.6,68.1,13996.0,-1.9
Helsingin seutukunta,111.8,73.6,1536926.0,1.2
Hämeenlinnan seutukunta,142.4,71.6,93879.0,-0.4
...,...,...,...,...
Ylä-Savon seutukunta,165.8,67.6,54307.0,-1.4
Äänekosken seutukunta,179.7,65.6,21892.0,-1.1
Åboland-Turunmaan seutukunta,147.3,74.5,22078.0,-0.9
Ålands landsbygd,96.5,85.0,15756.0,1.5
Ålands skärgård,118.7,82.7,2056.0,-3.1

In [15]:
#erotellaan maakunnat
maakunnat = df.iloc[1244:1320]
maakunnat = maakunnat.pivot(index="Kaupunki", columns="Tilasto", values="2017")
maakunnat

Tilasto,Taloudellinen huoltosuhde,"Työllisyysaste, %",Väkiluku,"Väkiluvun muutos edellisestä vuodesta, %"
Kaupunki,,,,
Ahvenanmaa,100.0,83.1,29489.0,0.9
Etelä-Karjalan maakunta,160.7,66.3,129865.0,-0.5
Etelä-Pohjanmaan maakunta,147.7,71.9,190910.0,-0.5
Etelä-Savon maakunta,168.5,66.8,147194.0,-1.2
Kainuun maakunta,170.5,65.1,73959.0,-1.1
Kanta-Hämeen maakunta,142.5,71.5,172720.0,-0.6
Keski-Pohjanmaan maakunta,146.2,72.7,68780.0,-0.4
Keski-Suomen maakunta,154.1,66.8,276031.0,-0.1
Kymenlaakson maakunta,166.3,65.9,175511.0,-1.2
Lapin maakunta,154.7,67.2,179223.0,-0.5
Pirkanmaan maakunta,137.7,69.8,512081.0,0.5
Pohjanmaan maakunta,130.2,75.3,180945.0,-0.3
Pohjois-Karjalan maakunta,169.6,63.5,162986.0,-0.7
Pohjois-Pohjanmaan maakunta,153.5,67.7,411856.0,0.2
Pohjois-Savon maakunta,152.4,67.5,246653.0,-0.5
Päijät-Hämeen maakunta,156.6,67.9,201228.0,-0.2
Satakunnan maakunta,151.4,70.1,220398.0,-0.6
Uudenmaan maakunta,113.4,73.6,1655624.0,1.1
Varsinais-Suomen maakunta,135.1,70.9,477677.0,0.4

# Tilastojen analysointi

In [17]:
#Population of capital region
kaupungit.loc[["Helsinki","Espoo", "Vantaa", "Kauniainen"]]["Väkiluku"]

Kaupunki
Helsinki      643272.0
Espoo         279044.0
Vantaa        223027.0
Kauniainen      9624.0
Name: Väkiluku, dtype: float64

In [18]:
#Population of capital region
print("Capital region population:",kaupungit.loc[["Helsinki","Espoo", "Vantaa", "Kauniainen"]]["Väkiluku"].sum())

Capital region population: 1154967.0

In [25]:
#What is the municipality where the minimun population resides
maakunnat.sort_values(by=["Väkiluku"],ascending=False)["Väkiluku"]

Kaupunki
Uudenmaan maakunta             1655624.0
Pirkanmaan maakunta             512081.0
Varsinais-Suomen maakunta       477677.0
Pohjois-Pohjanmaan maakunta     411856.0
Keski-Suomen maakunta           276031.0
Pohjois-Savon maakunta          246653.0
Satakunnan maakunta             220398.0
Päijät-Hämeen maakunta          201228.0
Etelä-Pohjanmaan maakunta       190910.0
Pohjanmaan maakunta             180945.0
Lapin maakunta                  179223.0
Kymenlaakson maakunta           175511.0
Kanta-Hämeen maakunta           172720.0
Pohjois-Karjalan maakunta       162986.0
Etelä-Savon maakunta            147194.0
Etelä-Karjalan maakunta         129865.0
Kainuun maakunta                 73959.0
Keski-Pohjanmaan maakunta        68780.0
Ahvenanmaa                       29489.0
Name: Väkiluku, dtype: float64

In [27]:
maakunnat.sort_values(by=["Työllisyysaste, %"],ascending=False)["Työllisyysaste, %"]

Kaupunki
Ahvenanmaa                     83.1
Pohjanmaan maakunta            75.3
Uudenmaan maakunta             73.6
Keski-Pohjanmaan maakunta      72.7
Etelä-Pohjanmaan maakunta      71.9
Kanta-Hämeen maakunta          71.5
Varsinais-Suomen maakunta      70.9
Satakunnan maakunta            70.1
Pirkanmaan maakunta            69.8
Päijät-Hämeen maakunta         67.9
Pohjois-Pohjanmaan maakunta    67.7
Pohjois-Savon maakunta         67.5
Lapin maakunta                 67.2
Keski-Suomen maakunta          66.8
Etelä-Savon maakunta           66.8
Etelä-Karjalan maakunta        66.3
Kymenlaakson maakunta          65.9
Kainuun maakunta               65.1
Pohjois-Karjalan maakunta      63.5
Name: Työllisyysaste, %, dtype: float64

In [29]:
kaupungit.sort_values(by=["Työllisyysaste, %"],ascending=False)["Työllisyysaste, %"]

Kaupunki
Jomala        87.2
Vårdö         86.8
Lumparland    86.7
Lemland       85.2
Föglö         85.0
              ...
Lieksa        57.6
Rautavaara    57.5
Kaavi         57.0
Rääkkylä      56.6
Puolanka      56.1
Name: Työllisyysaste, %, Length: 311, dtype: float64